name: chronos
description: Custom true time clock based on hardware monotonic time.
version: 1.0.0

environment:
  sdk: ^3.13.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mocktail: ^1.0.5
  shared_preferences: ^2.3.0
  # timezone: ^0.9.4

flutter:
  plugin:
    platforms:
      android:
        package: com.chronos
        pluginClass: ChronosPlugin
      ios:
        pluginClass: ChronosPlugin
dev_dependencies:
  flutter_test:
    sdk: flutter
